### ISSUE TITLE
Migration to Monorepo & NPM Workspaces & pnpm

### ISSUE THREAD

**Issue by andyslack** [juicyllama-npm/core#116]
Look at how we can simplify: https://docs.google.com/document/d/1YKjjD0s972_YbCHeRuMOqMahUMoOb8XpQIxngV5m5hg/edit

**Comment by yossi-shasho** [comment]
@andyslack I went over the guide you attached in Medium. Looks solid. IMO the right thing to do would be to begin and solve the problems as we encounter them. The tech seems mature enough.

**Comment by andyslack** [comment]
Hi @yossi-shasho 

Please use this repo as the main one for this: https://github.com/juicyllama/framework

All the repos from https://github.com/orgs/juicyllama-npm should be moved over. We can then close that org down and have everything in the https://github.com/orgs/juicyllama org.

Please use the following structure:

packages/nestjs/{package} for current nestjs moduels (core, billing, crm, etc) 
packages/nestjs/apps/{name} e.g. packages/apps/wordpress
packages/nestjs/tools/{name} e.g. packages/tools/shortlinks
packages/vue/{name} e.g. packages/vue/utils, quasar, dev

This will give us more scope for using different tooling/frameworks in the future where/if needed.

**Comment by yossi-shasho** [comment]
@andyslack Sure, However its seems that I have no access privileges to https://github.com/juicyllama/framework

**Comment by andyslack** [comment]
I have created a teams account on codesandbox.io so we can integrate this into the GitHub process (releasing, code reviews etc)

https://codesandbox.io/docs/learn/integrations/github-app

This should solve our NPM release issue with versioning also.

**Comment by andyslack** [comment]
Moved to: https://github.com/orgs/juicyllama/projects/8?pane=issue&itemId=38707465
