### ISSUE TITLE
Add Filters to controller/service/test abstraction

### ISSUE THREAD

**Issue by andyslack** [juicyllama-npm/core#94]
This ticket is building on https://github.com/juicyllama-npm/core/issues/91

We are looking to implement a abstraction for filtering globally, we can reuse the ${service}Select enums from the module constants.ts for documentation showing what fields exists in the filter. 

The filters apply to:

- List
- Stats
- Charts

The controller should look for (looping over the Select Enum) for the objects in the query param for params matching the field name

This utils helper may help with this, or you can add a new function to it: 

https://github.com/juicyllama-npm/utils/blob/main/src/utils/Enums.ts you can see the implementation here: https://github.com/juicyllama-npm/utils/blob/main/src/utils/Enums.test.spec.ts

The query param should be in the following format:

&FIELD=FILTER:VALUE

e.g. 

&amount=GTE:100&amount=!NULL

note, each field can have multiple values passed.

More details here: https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#rhs-colon

The following FILTERS should be supported:

- GTE
- LTE
- EQ
- !EQ
- NULL
- !NULL

We should ensure the swagger documentation for the endpoints reflect the above.

This task will need:

Updating crud endpoints for List, Stats, Charts, example here https://github.com/juicyllama-npm/core/blob/main/src/helpers/crudController.ts#L47 plus the abstracted service alongside.

The accompanying helper decorators e.g. https://github.com/juicyllama-npm/core/blob/main/src/decorators/crud.decorator.ts#L75

The testing endpoint for automated testing of passing filters - https://github.com/juicyllama-npm/core/blob/main/src/test/helpers.ts

Finally, can you add the new endpoint/details to the relevant documentation, here are some places it may apply: 

1.  https://docs.juicyllama.com/backend/core/decorators/crud.html
2. https://docs.juicyllama.com/backend/core/helpers/controller.html
3. https://docs.juicyllama.com/backend/core/helpers/service.html
4. https://docs.juicyllama.com/backend/core/testing/

**Comment by yossi-shasho** [comment]
@andyslack how would values look with !NULL or NULL, because these operators don't accept a value so the query param won't be of the template `OPERATOR:VALUE`

**Comment by andyslack** [comment]
Thats correct, if the OPERATOR = !NULL or NULL we don't need to look for or expect a VALUE

**Comment by yossi-shasho** [comment]
@andyslack I finished the main chunk of the feature - logic and specs. it came out quite elegant and without too much code, but in fact it wasn't that easy. lots of code has been deleted and rewritten in the process, but I'm now a much better typeORM coder!

**Comment by yossi-shasho** [comment]
![Image](https://github.com/juicyllama-npm/core/assets/1956748/db2e303a-7353-4c0a-b30c-ac13429845dd)

**Comment by yossi-shasho** [comment]
@andyslack 

I'm posting this before the feature is done because I'd like you to take a look at the code before I go on with finalizing the feature
https://github.com/juicyllama-npm/core/compare/feature/94-filtering-abstraction?expand=1

One improvement I'm going to make is to move/duplicate the specs into `Query.test.spec.ts` unless you have a better idea.

![Image](https://github.com/juicyllama-npm/core/assets/1956748/5d488929-e454-4f47-879a-83682c9b32bc)

**Comment by andyslack** [comment]
Sounds like a great idea! Nice work

**Comment by yossi-shasho** [comment]
@andyslack regarding the decorators: as of now, neither the docs nor the decorators seem to mention that it's possible to send any column from the table as a query parameter to look by exact value e.g. `account_name=hive` in the findAll, stats and charts endpoints, and this behavior was already supported. How would you like the docs to look like?

![Image](https://github.com/juicyllama-npm/core/assets/1956748/fd2d7727-777c-4f62-b29f-b9fff7e72b28)

**Comment by andyslack** [comment]
Hi @yossi-shasho good catch, let's add this at the same time to the docs as the work on this ticket.

It would be amazing if you can document these with the abstraction also.

**Comment by yossi-shasho** [comment]
@andyslack I'm not sure I understood your answer; I'm actually asking do you imagine the docs to end up looking like. I attached a screenshot of the older docs to demonstrate that the existing filtering is missing from it.

**Comment by andyslack** [comment]
Correct, we should add them.

Also RE the filters, I suggest we use the endpoint descriptions to pass in a list of possible filters and an explanation of how they work?

**Comment by yossi-shasho** [comment]
absolutely agree regarding the docs. new regarding the decorators, IMO a cool way to do it might be to call `ApiQuery` in loop over an array of field names. WDYT? @andyslack 
<img width="1062" alt="image" src="https://github.com/juicyllama-npm/core/assets/1956748/4e7f4e18-1b90-4753-a47c-130c6e102f52">

**Comment by andyslack** [comment]
Sounds like a great idea! You can use the entity to get the fields and use this, this way there is no need got the select enum at all

**Comment by yossi-shasho** [comment]
@andyslack do you think its safe to use the entity? e.g. maybe some fields that we're supposed to filter by might slip in? I'm not sure its even a risk

**Comment by andyslack** [comment]
I don't think it should be an issue for filtering, if it is in the future we can refactor?

**Comment by yossi-shasho** [comment]
Hey @andyslack 
The feature is ready! you can review and PRs:
https://github.com/juicyllama-npm/core/pull/111
https://github.com/juicyllama-npm/utils/pull/45

The CSV feature is branched out of this feature so let's first get done with this one.

here's out it came out.
![Image](https://github.com/juicyllama-npm/core/assets/1956748/c78615a5-7aca-4770-a581-5c8c139d390b)

**Comment by andyslack** [comment]
Hi @yossi-shasho I've merged these and released them both live. 

Are you also able to update and release hive so I can see this live inside the live project and released.

Cheers mate

**Comment by andyslack** [comment]
@yossi-shasho 

started getting this on documents since pushing latest version live:

https://api.sentinel.hiveuw.com/

I believe it must be related to this task?



![Image](https://github.com/juicyllama-npm/core/assets/3747768/c0305ab8-595a-44da-a9c5-7c4693f341e9)

**Comment by yossi-shasho** [comment]
@andyslack on one hand it makes sense that the recent change broke it; on the other hand it did work perfectly fine on my machine and now after I pulled the last released version it no longer works. I can look into it but I need a hint: how does redoc works in this case? afaik it should be reading from a json, yaml or swagger file. where is it located?

**Comment by yossi-shasho** [comment]
@andyslack it was a bug in the `UploadCSVDecorator`, fixed now. see PR: https://github.com/juicyllama-npm/core/pull/114/files

**Comment by andyslack** [comment]
@shershen08 we should discuss how to build this into the `JLTable` schema so we can pass these filters in.

**Comment by andyslack** [comment]
@yossi-shasho working now, thanks :)
