### ISSUE TITLE
CSV Upload / Mapping Abstraction

### ISSUE THREAD

**Issue by andyslack** [juicyllama-npm/core#96]
Building on both:

https://github.com/juicyllama-npm/core/issues/91
https://github.com/juicyllama-npm/core/issues/94

We are looking to create a similar abstraction layer for CSV importing. Allowing charting endpoints to be easily implemented across our framework.

This task will need:

A crudUploadCSVFile function similar to the others here https://github.com/juicyllama-npm/core/blob/main/src/helpers/crudController.ts#L47 plus the abstracted service alongside.

The accompanying decorator helper similar to this one https://github.com/juicyllama-npm/core/blob/main/src/decorators/crud.decorator.ts#L75

The testing endpoint for automated testing of the new controller here - https://github.com/juicyllama-npm/core/blob/main/src/test/helpers.ts

The controller should support the following:

file: A CSV file upload, you can see how we do this for avatars (also abstracted here): https://github.com/juicyllama-npm/core/blob/main/src/modules/users/users.controller.ts#L125
mappers: string[]
skip_first: boolean (if to ignore the first row)

Each mappers(x) in array matches the column in the file and puts the value into the DB matching the name on the array

Eg `name, description, amount`

Puts col A value in name field 
Col B value in description field 

Once done, we will need to implement the [Quasar component to take the CSV, read and process the mapping](https://github.com/juicyllama-npm/quasar/issues/142).

**Comment by yossi-shasho** [comment]
PR is ready. https://github.com/juicyllama-npm/core/pull/112 
Lets make sure we merge the filtering PR before this one

**Comment by andyslack** [comment]
MOVED TO: https://github.com/orgs/juicyllama/projects/8?pane=issue&itemId=38707206
